# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        "api",
        "api.app",
        "api.routes",
        "core",
        "core.event_bus",
        "core.services",
        "core.state",
        "core.workspace",
        "geometry",
        "geometry.volume",
        "geometry.curvature",
        "mcp_server",
        "mcp_server.server",
        "mcp_server.api_client",
        "mcp_server.workspace_access",
        "mcp_client",
        "mcp_client.client",
        "common.types",
        "common.events",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
